redis:
  image: redis:3.0.7
web:
  image: ${IMAGE_NAME}
  environment:
    - REDIS_URL=redis://redis
  volumes:
    - .:/app
  ports:
    - "3000"
  links:
    - redis
  labels:
   - "traefik.backend=search-for-member"
   - "traefik.frontend.rule=Host:sfm.ukpds.org"